# ingress:
#   enabled: true
#   host:
#      name: "jenkins.localhost"

servicePort: 8080
targetPort: 8080

persistence:
  enabled: false

controller:
  admin:
    password: admin
    username: admin
  
  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to Kube-Jenkins!

  # # LOCAL ONLY:
  serviceType: LoadBalancer
