apiVersion: v1
kind: Namespace
metadata:
  name: weather
---
apiVersion: v1
kind: Service
metadata:
  name: weather
  namespace: weather
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: weather
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: thevanguardian/weather:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: app.py
        - name: FLASK_ENV
          value: production
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi